### ISSUE TITLE
Python `requests` package on the node?

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/nodecontroller#4]
I just want to make sure that the Python `requests` package is on the node. This is a very useful library for doing any kind of data fetching over HTTP(S).

Reference:
http://docs.python-requests.org/en/master/

**Comment by MuffinSpawn** [comment]
Moving to the development repo...

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #15](https://github.com/waggle-sensor/development/issues/15) via [**ZenHub**](https://www.zenhub.com/)
