### ISSUE TITLE
Need to get waggle_protocol sorted out.

### ISSUE THREAD

**Issue by seanshahkarami** [waggle-sensor/nodecontroller#5]
It appears that the submodule `waggle_protocol` is not being pulled correctly with the `nodecontroller` repo. I witnessed one of the CDOT nodes not sending data because of this. A simple symbolic link to the other `waggle_protocol` in the `plugin_manager`.

**Comment by wcatino** [comment]
I think you use "git submodule update" for that, possibly preceded by a
"git submodule init" or "git submodule --init".
These commands appear in beehive code, maybe grep for them.
Hope this helps.

**Comment by seanshahkarami** [comment]
Thanks, Bill. I thought I remember doing some other command with submodule. I forgot about the `--init` argument... I'll have to try that again at some point.

**Comment by MuffinSpawn** [comment]
Sean, I assigned this to you for comment. Has this been resolved? If so, please close the issue. Thanks!

**Comment by seanshahkarami** [comment]
This doesn't seem to have given me a problem lately. I'd argue the way to ensure that this never occurs again is to just use `pywaggle.protocol`. I can ensure that's happening relatively quickly.

**Comment by seanshahkarami** [comment]
Just to be clear, I'm not sure what changed that seems to have stopped that from happening, though, which is why I'm hesitant to close this.

**Comment by MuffinSpawn** [comment]
I'll move this to the development repo, then. I'm consolidate issues there.

**Comment by MuffinSpawn** [comment]
Issue moved to [waggle-sensor/development #14](https://github.com/waggle-sensor/development/issues/14) via [**ZenHub**](https://www.zenhub.com/)
